bug: Fix use-after-free bug in `edge::Gateway`
storj-thirdparty/uplink-rust pull request #80
Opened 2024-11-11 01:10 UTC by GodTamIt

Previously, `from_ffi_credentials_result()` would free the underlying memory of the strings stored in `Gateway` (the FFI `EdgeCredentialsResult`) upon success, resulting in a use-after-free error for anyone trying to access those strings.

2024-11-11 01:27 UTC, GodTamIt commented
fyi @ifraixedes - this is potentially a security vulnerability.

2024-11-11 15:24 UTC, ifraixedes requested changes
@GodTamIt good catch!

I detected these issues when I wrote one of the first integration tests. When I realized the problem, I changed all of them to types that Rust owns rather than dragging references to C pointers.

I changed all of those structs that I found however, I missed some that I changed when later I realized (e.g. https://github.com/storj-thirdparty/uplink-rust/commit/9bb1cfbfcc6412059c5ae2ab7ec9eae2b3b7d9c5). 

I missed this one. One of the reasons is that there is no integration test for it https://github.com/storj-thirdparty/uplink-rust/blob/main/uplink/tests/edge_test.rs#L8

Thank you very much for your contribution.

2024-11-11 16:35 UTC, GodTamIt commented
@ifraixedes yep, all done!

Thanks for the quick reviews :)

2024-11-12 17:00 UTC, ifraixedes commented
> Aside: for some of the memory freeing code paths, what's your opinion on using something like scopeguard so that memory always gets cleaned up (RAII style)?

I got a suggestion when I talked about building this in a meetup. They said:

> Because you cannot implement the `Drop` trait for the types generated by bindgen, you could implement a wrapper type for each of them and implement the `Drop` trait.

I stated it as a good idea. Unfortunately, I didn't think about it when I implemented it :grimacing: 

Did I respond to your question?

2024-11-12 17:01 UTC, ifraixedes approved these changes

2024-11-12 17:07 UTC, ifraixedes approved these changes

2024-11-12 17:14 UTC, GodTamIt commented
> > Aside: for some of the memory freeing code paths, what's your opinion on using something like scopeguard so that memory always gets cleaned up (RAII style)?
> 
> I got a suggestion when I talked about building this in a meetup. They said:
> 
> > Because you cannot implement the `Drop` trait for the types generated by bindgen, you could implement a wrapper type for each of them and implement the `Drop` trait.
> 
> I stated it as a good idea. Unfortunately, I didn't think about it when I implemented it 😬
> 
> Did I respond to your question?

Yeah that does. If I have some time, I could explore doing something like that. Otherwise, the library is working as intended so not critical. Just helps prevent leaks and bugs :)

2024-11-12 17:35 UTC, ifraixedes commented
You'll need to rebase once I merge https://github.com/storj-thirdparty/uplink-rust/pull/82
I'm waiting for reviews.

2024-11-12 17:45 UTC, ifraixedes commented
@GodTamIt it's merged.

2024-11-12 17:52 UTC, GodTamIt commented
@ifraixedes it's rebased

2024-11-13 10:50 UTC, merged

2024-11-13 10:51 UTC, ifraixedes commented
I will make a new release later today or tomorrow.
Thank you for your contribution.